$ANSIBLE_VAULT;1.1;AES256
66366566306431633034636563333366633737633937373063663564383664636166303037626538
3464323239383035343936303431643334626432346365660a306165326433396266666432643533
39623238623362316439396362356430633730363330303635383734323732643962323531313739
6164653739643661300a323363616437646465643439303831633034353461363934323162396665
39346331383736336562633032633863613733396339653964333637616464663434383663303739
30343334666563343564326532636464356533313139303836323537336166653333663334653266
63333964656563373139383137313239343661313531353464343033633735363062666237636433
66383430316562333733333862613437383138393339623134323036653963643236636638333438
66356462346264386436376331633862313037343863383861613162313737376539396533353765
64336534613130656331383061363737356538376338336331663437653365336361623036616663
366663346331373630376366376438623339
